version: '3'
services:
  app:
    image: alexsouzasilva/ms-find-car:latest
    container_name: ms-find-car
    volumes:
      - ./target/ms-find-car.jar:/app/app.jar
    working_dir: /app
    command: ["java", "-jar", "app.jar"]
    ports:
      - "8570:8570"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Defina uma senha para o admin

networks:
  monitoring:
    driver: bridge

# Acesse Prometheus: http://localhost:9090
