server:
    port: 8570

management:
    endpoints:
        web:
            exposure:
                include: '*'
            base-path: /
    endpoint:
        metrics:
            enabled: true



