apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: kubeapp

images:
- name: ms-find-car
  newName: alexsouzasilva/ms-find-car
  newTag: latest